In [2]:
%matplotlib inline


PyTorch是什么?
================

基于Python的科学计算包，服务于以下两种场景:

-  作为NumPy的替代品，可以使用GPU的强大计算能力
-  提供最大的灵活性和高速的深度学习研究平台
    

开始
---------------

Tensors（张量）

Tensors与Numpy中的 ndarrays类似，但是在PyTorch中
Tensors 可以使用GPU进行计算.



In [3]:
from __future__ import print_function
import torch

创建一个 5x3 矩阵, 但是未初始化:



In [22]:
x = torch.empty(5, 3)
print(x)

tensor([[9.5510e-39, 1.0837e-38, 1.0102e-38],
        [8.4490e-39, 9.6428e-39, 8.4490e-39],
        [9.6429e-39, 9.2755e-39, 1.0286e-38],
        [9.0919e-39, 8.9082e-39, 9.2755e-39],
        [8.4490e-39, 1.0194e-38, 9.0919e-39]])


创建一个随机初始化的矩阵:



In [23]:
x = torch.rand(5, 3)
print(x)

tensor([[0.2853, 0.3472, 0.2556],
        [0.0180, 0.0680, 0.9985],
        [0.9873, 0.9177, 0.9852],
        [0.9715, 0.3299, 0.7989],
        [0.0350, 0.6543, 0.2074]])


创建一个0填充的矩阵，数据类型为long:



In [6]:
x = torch.zeros(5, 3, dtype=torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


创建tensor并使用现有数据初始化:



In [24]:
x = torch.tensor([5.5, 3,10.2])
print(x)

tensor([ 5.5000,  3.0000, 10.2000])


根据现有的张量创建张量。 这些方法将重用输入张量的属性，例如， dtype，除非设置新的值进行覆盖

In [8]:
x = x.new_ones(5, 3, dtype=torch.double)      # new_* 方法来创建对象
print(x)

x = torch.randn_like(x, dtype=torch.float)    # 覆盖 dtype!
print(x)                                      #  对象的size 是相同的，只是值和类型发生了变化

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]], dtype=torch.float64)
tensor([[ 1.9071, -0.9157, -1.1217],
        [ 0.6306, -0.7646,  0.1204],
        [-0.6917,  0.9884, -1.2882],
        [ 0.2884, -0.6867,  1.5034],
        [-0.0252, -1.5339, -0.8444]])


获取 size

***译者注：使用size方法与Numpy的shape属性返回的相同，张量也支持shape属性，后面会详细介绍***


In [25]:
print(x.size())

torch.Size([3])


<div class="alert alert-info"><h4>Note</h4><p>``torch.Size`` 返回值是 tuple类型, 所以它支持tuple类型的所有操作.</p></div>

操作

操作有多种语法。 

我们将看一下加法运算。

加法1:

In [26]:
y = torch.rand(5, 3)
print(x + y)

tensor([[ 6.3197,  3.0059, 10.2456],
        [ 6.2125,  3.0231, 10.7704],
        [ 5.8433,  3.9826, 10.2626],
        [ 5.5181,  3.7487, 10.7731],
        [ 5.6301,  3.5619, 10.6045]])


加法2


In [11]:
print(torch.add(x, y))

tensor([[ 2.8144, -0.6060, -0.2620],
        [ 1.4181, -0.4012,  0.9805],
        [-0.0131,  1.9492, -1.1641],
        [ 1.1981, -0.4015,  2.2696],
        [ 0.5238, -0.7702, -0.0811]])


提供输出tensor作为参数



In [27]:
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 6.3197,  3.0059, 10.2456],
        [ 6.2125,  3.0231, 10.7704],
        [ 5.8433,  3.9826, 10.2626],
        [ 5.5181,  3.7487, 10.7731],
        [ 5.6301,  3.5619, 10.6045]])


替换



In [13]:
# adds x to y
y.add_(x)
print(y)

tensor([[ 2.8144, -0.6060, -0.2620],
        [ 1.4181, -0.4012,  0.9805],
        [-0.0131,  1.9492, -1.1641],
        [ 1.1981, -0.4015,  2.2696],
        [ 0.5238, -0.7702, -0.0811]])


<div class="alert alert-info"><h4>Note</h4><p>任何 以``_`` 结尾的操作都会用结果替换原变量.
    例如: ``x.copy_(y)``, ``x.t_()``, 都会改变 ``x``.</p></div>

你可以使用与NumPy索引方式相同的操作来进行对张量的操作



In [14]:
print(x[:, 1])

tensor([-0.9157, -0.7646,  0.9884, -0.6867, -1.5339])


``torch.view``: 可以改变张量的维度和大小

***译者注：torch.view 与Numpy的reshape类似***



In [15]:
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1, 8)  #  size -1 从其他维度推断
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


如果你有只有一个元素的张量，使用``.item()``来得到Python数据类型的数值


In [16]:
x = torch.randn(1)
print(x)
print(x.item())

tensor([0.8539])
0.8539153933525085


**Read later:**


  100+ Tensor operations, including transposing, indexing, slicing,
  mathematical operations, linear algebra, random numbers, etc.,
  are described
  `here <https://pytorch.org/docs/torch>`_.

NumPy 转换
------------

将一个Torch Tensor转换为NumPy数组是一件轻松的事，反之亦然。

Torch Tensor与NumPy数组共享底层内存地址，修改一个会导致另一个的变化。

将一个Torch Tensor转换为NumPy数组



In [17]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [18]:
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


观察numpy数组的值是如何改变的。



In [19]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


 NumPy Array 转化成 Torch Tensor

使用from_numpy自动转化



In [20]:
import numpy as np
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)



所有的 Tensor 类型默认都是基于CPU， CharTensor 类型不支持到
NumPy 的转换.
CUDA 张量
------------

使用``.to`` 方法 可以将Tensor移动到任何设备中



In [29]:
# is_available 函数判断是否有cuda可以使用
# ``torch.device``将张量移动到指定的设备中
if torch.cuda.is_available():
    device = torch.device("cuda")          # a CUDA 设备对象
    y = torch.ones_like(x, device=device)  # 直接从GPU创建张量
    x = x.to(device)                       # 或者直接使用``.to("cuda")``将张量移动到cuda中
    z = x + y
    print(z)
    print(z.to("cpu", torch.double))       # ``.to`` 也会对变量的类型做更改
else:
    print("cuda is not support")

cuda is not support
